/**
 * The contents of this file are subject to the OpenMRS Public License
 * Version 1.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at
 * http://license.openmrs.org
 *
 * Software distributed under the License is distributed on an "AS IS"
 * basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
 * License for the specific language governing rights and limitations
 * under the License.
 *
 * Copyright (C) OpenMRS, LLC.  All Rights Reserved.
 */
package org.openmrs.module.report.service;

import java.util.Collection;
import java.util.List;

import org.openmrs.api.APIException;
import org.openmrs.api.OpenmrsService;
import org.openmrs.module.evaluation.EvaluationContext;
import org.openmrs.module.report.ReportData;
import org.openmrs.module.report.ReportDefinition;
import org.openmrs.module.report.ReportDesign;
import org.openmrs.module.report.renderer.RenderingMode;
import org.openmrs.module.report.renderer.ReportRenderer;
import org.springframework.transaction.annotation.Transactional;

/**
 * ReportService API
 */
@Transactional
public interface ReportService extends OpenmrsService {
	
	/**
	 * This method evaluates a ReportDefinition object for the given EvaluationContext and input Cohort.
	 * It returns the ReportData object which contains the Report "results".
	 * 
	 * @param reportDefinition - The {@link ReportDefinition}
	 * @param context - The {@link EvaluationContext} which contains the parameters, provides caching for the report evaluation
	 * @return {@link ReportData} - Contains the evaluated report data
	 * @throws APIException
	 */
	public ReportData evaluate(ReportDefinition reportDefinition, EvaluationContext context);
	
	/**
	 * Return a list of {@link ReportDefinition}s
	 * 
	 * @return a List<ReportDefinition> object containing all of the {@link ReportDefinition}s
	 * @throws APIException
	 */
	@Transactional(readOnly = true)
	public List<ReportDefinition> getReportDefinitions() throws APIException;
	
	/**
	 * Return a list of {@link ReportDefinition}s, optionally including those that are retired
	 * @param includeRetired if true, indicates that retired {@link ReportDefinition}s should also be included
	 * @return a List<ReportDefinition> object containing all of the {@link ReportDefinition}s
	 * @throws APIException
	 */
	@Transactional(readOnly = true)
	public List<ReportDefinition> getReportDefinitions(boolean includeRetired) throws APIException;
	
	/**
	 * @param uuid
	 * @return the ReportDefinition with the given uuid
	 */
	@Transactional(readOnly = true)
	public ReportDefinition getReportDefinitionByUuid(String uuid) throws APIException;
	
	/**
	 * Returns either a saved ReportDefinition with the passed uuid, or a new ReportDefinition of the passed type
	 */
	@Transactional(readOnly = true)
    public ReportDefinition getReportDefinition(String uuid, Class<? extends ReportDefinition> type);
	
	/**
	 * Get the {@link ReportDefinition} with the given id
	 * 
	 * @param reportDefinitionId The Integer ReportDefinition id
	 * @return the matching {@link ReportDefinition} object
	 * @throws APIException
	 */
	@Transactional(readOnly = true)
	public ReportDefinition getReportDefinition(Integer reportDefinitionId) throws APIException;
	
	/**
	 * Save or update the given <code>ReportDefinition</code> in the database. If this is a new
	 * ReportDefinition, the returned ReportDefinition will have a new
	 * {@link ReportDefinition#getReportDefinitionId()} inserted into it that was generated by the database
	 * 
	 * @param reportDefinition The <code>ReportDefinition</code> to save or update
	 * @throws APIException
	 */
	public ReportDefinition saveReportDefinition(ReportDefinition reportDefinition) throws APIException;
	
	/**
	 * Deletes a <code>ReportDefinition</code> from the database.
	 * 
	 * @param reportDefinition The <code>ReportDefinition</code> to remove from the system
	 * @throws APIException
	 */
	public void deleteReportDefinition(ReportDefinition reportDefinition);
	
	/**
	 * @param uuid
	 * @return the ReportDesign with the given uuid
	 */
	@Transactional(readOnly = true)
	public ReportDesign getReportDesignByUuid(String uuid) throws APIException;
	
	
	/**
	 * Get the {@link ReportDesign} with the given id
	 * 
	 * @param id The Integer ReportDesign id
	 * @return the matching {@link ReportDesign} object
	 * @throws APIException
	 */
	@Transactional(readOnly = true)
	public ReportDesign getReportDesign(Integer id) throws APIException;
	
	/**
	 * Return a list of {@link ReportDesign}s, optionally including those that are retired
	 * @param includeRetired if true, indicates that retired {@link ReportDesign}s should also be included
	 * @return a List<ReportDesign> object containing all of the {@link ReportDesign}s
	 * @throws APIException
	 */
	@Transactional(readOnly = true)
	public List<ReportDesign> getAllReportDesigns(boolean includeRetired) throws APIException;
	
	/**
	 * Return a list of {@link ReportDesign}s for {@link ReportDefinition} that match the passed parameters
	 * Each input parameter can be null, restricting the returned results only if it is not null.  This allows you
	 * to retrieve all ReportDesigns by ReportDefinition, by RendererType, by retired status, or a combination of these
	 * criteria.
	 * @param reportDefinitionId if not null, only {@link ReportDesign}s for this {@link ReportDefinition} will be returned
	 * @param rendererType if not null, only {@link ReportDesign}s for this {@link ReportRenderer} type will be returned
	 * @param includeRetired if true, indicates that retired {@link ReportDesign}s should also be included
	 * @return a List<ReportDesign> object containing all of the {@link ReportDesign}s
	 * @throws APIException
	 */
	@Transactional(readOnly = true)
	public List<ReportDesign> getReportDesigns(ReportDefinition reportDefinition, Class<? extends ReportRenderer> rendererType, 
											   boolean includeRetired) throws APIException;
	
	/**
	 * Save or update the given <code>ReportDesign</code> in the database. If this is a new
	 * ReportDesign, the returned ReportDesign will have a new
	 * {@link ReportDesign#getId()} inserted into it that was generated by the database
	 * 
	 * @param reportDesign The <code>ReportDesign</code> to save or update
	 * @throws APIException
	 */
	public ReportDesign saveReportDesign(ReportDesign reportDesign) throws APIException;
	
	/**
	 * Purges a <code>ReportDesign</code> from the database.
	 * @param reportDesign The <code>ReportDesign</code> to remove from the system
	 * @throws APIException
	 */
	public void purgeReportDesign(ReportDesign reportDesign);
	
	/**
	 * Returns a Collection<ReportRenderer> of all registered ReportRenderers
	 * 
	 * @return All registered report renderers
	 */
	@Transactional(readOnly = true)
	public Collection<ReportRenderer> getReportRenderers();
	
	/**
	 * Returns the preferred ReportRenderer for the given class name.
	 * 
	 * @param objectType
	 * @return	the preferred ReportRenderer for the given class name
	 */
	@Transactional(readOnly = true)
	public ReportRenderer getReportRenderer(String className);
	
	/**
	 * Returns the preferred ReportRenderer for the given object type.
	 * 
	 * @param objectType
	 * @return	the preferred ReportRenderer for the given object type
	 */
	@Transactional(readOnly = true)
	public ReportRenderer getPreferredReportRenderer(Class<Object> objectType);
	
	
	/**
	 * Returns a List of {@link RenderingMode}s that the passed {@link ReportDefinition} supports, in
	 * their preferred order
	 * 
	 * @return all rendering modes for the given schema, in their preferred order
	 */
	@Transactional(readOnly = true)
	public List<RenderingMode> getRenderingModes(ReportDefinition schema);

	
}

