/**
 * The contents of this file are subject to the OpenMRS Public License
 * Version 1.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at
 * http://license.openmrs.org
 *
 * Software distributed under the License is distributed on an "AS IS"
 * basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
 * License for the specific language governing rights and limitations
 * under the License.
 *
 * Copyright (C) OpenMRS, LLC.  All Rights Reserved.
 */
package org.openmrs.module.report.service;

import java.util.Collection;
import java.util.List;
import java.util.Properties;

import org.openmrs.api.APIException;
import org.openmrs.api.OpenmrsService;
import org.openmrs.module.evaluation.EvaluationContext;
import org.openmrs.module.report.ReportData;
import org.openmrs.module.report.ReportDefinition;
import org.openmrs.module.report.renderer.RenderingMode;
import org.openmrs.module.report.renderer.ReportRenderer;
import org.springframework.transaction.annotation.Transactional;

/**
 * 
 */
@Transactional
public interface ReportService extends OpenmrsService {
	
	/**
	 * This method evaluates a ReportDefinition object for the given EvaluationContext and input Cohort.
	 * It returns the ReportData object which contains the Report "results".
	 * 
	 * @param reportDefinition - The {@link ReportDefinition}
	 * @param context - The {@link EvaluationContext} which contains the parameters, provides caching for the report evaluation
	 * @return {@link ReportData} - Contains the evaluated report data
	 * @throws APIException
	 */
	public ReportData evaluate(ReportDefinition reportDefinition, EvaluationContext context);
	
	/**
	 * Return a list of {@link ReportDefinition}s
	 * 
	 * @return a List<ReportDefinition> object containing all of the {@link ReportDefinition}s
	 * @throws APIException
	 */
	@Transactional(readOnly = true)
	public List<ReportDefinition> getReportDefinitions() throws APIException;
	
	/**
	 * @param uuid
	 * @return the ReportDefinition with the given uuid
	 */
	@Transactional(readOnly = true)
	public ReportDefinition getReportDefinitionByUuid(String uuid) throws APIException;	
	
	/**
	 * Get the {@link ReportDefinition} with the given id
	 * 
	 * @param reportDefinitionId The Integer ReportDefinition id
	 * @return the matching {@link ReportDefinition} object
	 * @throws APIException
	 */
	@Transactional(readOnly = true)
	public ReportDefinition getReportDefinition(Integer reportDefinitionId) throws APIException;
	
	/**
	 * Save or update the given <code>ReportDefinition</code> in the database. If this is a new
	 * ReportDefinition, the returned ReportDefinition will have a new
	 * {@link ReportDefinition#getReportDefinitionId()} inserted into it that was generated by the database
	 * 
	 * @param reportDefinition The <code>ReportDefinition</code> to save or update
	 * @throws APIException
	 */
	public ReportDefinition saveReportDefinition(ReportDefinition reportDefinition) throws APIException;
	
	/**
	 * Deletes a <code>ReportDefinition</code> from the database.
	 * 
	 * @param reportDefinition The <code>ReportDefinition</code> to remove from the system
	 * @throws APIException
	 */
	public void deleteReportDefinition(ReportDefinition reportDefinition);
	
	/**
	 * Returns a Collection<ReportRenderer> of all registered ReportRenderers
	 * 
	 * @return All registered report renderers
	 */
	@Transactional(readOnly = true)
	public Collection<ReportRenderer> getReportRenderers();
	
	/**
	 * Returns a List of {@link RenderingMode}s that the passed {@link ReportDefinition} supports, in
	 * their preferred order
	 * 
	 * @return all rendering modes for the given schema, in their preferred order
	 */
	@Transactional(readOnly = true)
	public List<RenderingMode> getRenderingModes(ReportDefinition schema);

	
	/**
	 * Gets the macros
	 * 
	 * @return macros
	 */
	@Transactional(readOnly = true)
	public Properties getReportXmlMacros();
	
	/**
	 * Saves the macros
	 * 
	 * @param macros the macros to set
	 */
	public void saveReportXmlMacros(Properties macros);
	
	/**
	 * Applies the report xml macros to the input, and returns it.
	 * 
	 * @param input The text (presumably a report schema xml definition) that you want to apply
	 *            macros to
	 * @return the result of applying macro substitutions to input
	 */
	public String applyReportXmlMacros(String input);

}

