/**
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at http://mozilla.org/MPL/2.0/. OpenMRS is also distributed under
 * the terms of the Healthcare Disclaimer located at http://openmrs.org/license.
 *
 * Copyright (C) OpenMRS Inc. OpenMRS is a registered trademark and the OpenMRS
 * graphic logo is a trademark of OpenMRS Inc.
 */
package org.openmrs.module.reporting.report.service.db;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.hibernate.Session;
import org.hibernate.query.MutationQuery;
import org.hibernate.query.Query;
import org.openmrs.api.db.DAOException;
import org.openmrs.api.db.hibernate.DbSessionFactory;
import org.openmrs.api.db.hibernate.HibernateUtil;
import org.openmrs.module.reporting.report.ReportDesign;
import org.openmrs.module.reporting.report.ReportProcessorConfiguration;
import org.openmrs.module.reporting.report.ReportRequest;
import org.openmrs.module.reporting.report.ReportRequest.Status;
import org.openmrs.module.reporting.report.definition.ReportDefinition;
import org.openmrs.module.reporting.report.renderer.ReportRenderer;

import java.util.Arrays;
import java.util.Collection;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * ReportService Database Access Interface
 */
public class HibernateReportDAO implements ReportDAO {
	
	protected final Log log = LogFactory.getLog(getClass());
	
	//***** PROPERTIES *****
	private DbSessionFactory sessionFactory;
	
	//***** INSTANCE METHODS *****
	
	//****** REPORT DESIGNS *****
	
	/**
	 * @param uuid
	 * @return the ReportDesign with the given uuid
	 */
	public ReportDesign getReportDesignByUuid(String uuid) throws DAOException {
		Query<ReportDesign> q = getSession().createQuery("from ReportDesign r where r.uuid = :uuid", ReportDesign.class);
		return q.setParameter("uuid", uuid).uniqueResult();
	}
	
	/**
	 * Get the {@link ReportDesign} with the given id
	 * @param id The Integer ReportDesign id
	 * @return the matching {@link ReportDesign} object
	 * @throws DAOException
	 */
	public ReportDesign getReportDesign(Integer id) throws DAOException {
		return getSession().get(ReportDesign.class, id);
	}
		
	/**
	 * Return a list of {@link ReportDesign}s for the passed {@link ReportDefinition} and {@link ReportRenderer} class,
	 * optionally including those that are retired
	 * @param includeRetired if true, indicates that retired {@link ReportDesign}s should also be included
	 * @return a List<ReportDesign> object containing all of the {@link ReportDesign}s
	 * @throws DAOException
	 */
	@SuppressWarnings("unchecked")
	public List<ReportDesign> getReportDesigns(ReportDefinition reportDefinition, Class<? extends ReportRenderer> rendererType, 
											   boolean includeRetired) throws DAOException {
		StringBuilder hql = new StringBuilder("from ReportDesign r where 1 = 1");
		Map<String, Object> params = new HashMap<String, Object>();
		if (reportDefinition != null) {
			hql.append(" and r.reportDefinition = :reportDefinition");
			params.put("reportDefinition", reportDefinition);
		}
		if (rendererType != null) {
			hql.append(" and r.rendererType = :rendererType");
			params.put("rendererType", rendererType);
		}
		if (includeRetired == false) {
			hql.append(" and r.retired = false");
		}
		Query<ReportDesign> q = getSession().createQuery(hql.toString(), ReportDesign.class);
		for (Map.Entry<String, Object> e : params.entrySet()) {
			q.setParameter(e.getKey(), e.getValue());
		}
		return q.list();
	}
	
	/**
	 * Save or update the given <code>ReportDesign</code> in the database. If this is a new
	 * ReportDesign, the returned ReportDesign will have a new
	 * {@link ReportDesign#getId()} inserted into it that was generated by the database
	 * 
	 * @param reportDesign The <code>ReportDesign</code> to save or update
	 * @throws DAOException
	 */
	public ReportDesign saveReportDesign(ReportDesign reportDesign) throws DAOException {
		return HibernateUtil.saveOrUpdate(getSession(), reportDesign);
	}
	
	/**
	 * Purges a <code>ReportDesign</code> from the database.
	 * @param reportDesign The <code>ReportDesign</code> to remove from the system
	 * @throws DAOException
	 */
	public void purgeReportDesign(ReportDesign reportDesign) {
		getSession().remove(reportDesign);
	}
	
	//****** REPORT PROCESSOR CONFIGURATIONS *****
	
	/**
	 * Saves a {@link ReportProcessorConfiguration} to the database and returns it
	 */
	public ReportProcessorConfiguration saveReportProcessorConfiguration(ReportProcessorConfiguration processorConfiguration) {
		return HibernateUtil.saveOrUpdate(getSession(), processorConfiguration);
	}

	/**
	 * @return the {@link ReportProcessorConfiguration} with the passed id
	 */
	public ReportProcessorConfiguration getReportProcessorConfiguration(Integer id) {
		return getSession().get(ReportProcessorConfiguration.class, id);
	}

	/**
	 * @return the {@link ReportProcessorConfiguration} with the passed uuid
	 */
	public ReportProcessorConfiguration getReportProcessorConfigurationByUuid(String uuid) {
		Query<ReportProcessorConfiguration> q = getSession().createQuery("from ReportProcessorConfiguration r where r.uuid = :uuid", ReportProcessorConfiguration.class);
		return q.setParameter("uuid", uuid).uniqueResult();
	}
	
	/**
	 * @return all the {@link ReportProcessorConfiguration}s
	 */
	@SuppressWarnings("unchecked")
	public List<ReportProcessorConfiguration> getAllReportProcessorConfigurations(boolean includeRetired) {
		String hql = "from ReportProcessorConfiguration r";
		if (includeRetired == false) {
			hql += " where r.retired = false";
		}
		return getSession().createQuery(hql, ReportProcessorConfiguration.class).list();
	}
	
	/**
	 * @return all the {@link ReportProcessorConfiguration}s that are meant to be applied globally, i.e., their reportDesign property is null
	 */
	@SuppressWarnings("unchecked")
	public List<ReportProcessorConfiguration> getGlobalReportProcessorConfigurations() {
		String hql = "from ReportProcessorConfiguration r where r.retired = false and r.reportDesign is null";
		return getSession().createQuery(hql, ReportProcessorConfiguration.class).list();
	}
	
	/**
	 * Deletes the passed {@link ReportProcessorConfiguration}
	 */
	public void purgeReportProcessorConfiguration(ReportProcessorConfiguration processorConfiguration) {
		getSession().remove(processorConfiguration);
	}
	
	//****** REPORT REQUESTS *****
	
	/**
	 * @see ReportDAO#saveReportRequest(ReportRequest)
	 */
	public ReportRequest saveReportRequest(ReportRequest request) {
		return HibernateUtil.saveOrUpdate(getSession(), request);
	}

	/**
	 * @see ReportDAO#getReportRequest(java.lang.Integer)
	 */
	public ReportRequest getReportRequest(Integer id) {
		return getSession().get(ReportRequest.class, id);
	}

	/**
	 * @see ReportDAO#getReportRequestByUuid(java.lang.String)
	 */
	public ReportRequest getReportRequestByUuid(String uuid) {
		Query<ReportRequest> q = getSession().createQuery("from ReportRequest r where r.uuid = :uuid", ReportRequest.class);
		return q.setParameter("uuid", uuid).uniqueResult();
	}

	/**
	 * @see ReportDAO#getReportRequests(ReportDefinition, Date, Date, Integer, Integer, Status...)
	 */
	@SuppressWarnings("unchecked")
	public List<ReportRequest> getReportRequests(ReportDefinition reportDefinition, Date requestOnOrAfter, Date requestOnOrBefore, Integer firstResult, Integer maxResults, Status...statuses) {
		Map<String, Object> params = new HashMap<String, Object>();
		String hql = "from ReportRequest r" + createReportRequestsWhereClause(params, reportDefinition, requestOnOrAfter, requestOnOrBefore, statuses)
				+ " order by r.requestDate desc, r.evaluateStartDatetime desc, r.evaluateCompleteDatetime desc, r.priority desc";
		Query<ReportRequest> query = getSession().createQuery(hql, ReportRequest.class);
		setParameters(query, params);

		if (firstResult != null) {
			query.setFirstResult(firstResult);
		}

		if(maxResults != null) {
			query.setMaxResults(maxResults);
		}

		return query.list();
	}

	@Override
	public long getReportRequestsCount(ReportDefinition reportDefinition, Date requestOnOrAfter, Date requestOnOrBefore, Status... statuses) {
		Map<String, Object> params = new HashMap<String, Object>();
		String hql = "select count(r) from ReportRequest r" + createReportRequestsWhereClause(params, reportDefinition, requestOnOrAfter, requestOnOrBefore, statuses);
		Query<Long> query = getSession().createQuery(hql, Long.class);
		setParameters(query, params);
		return query.uniqueResult();
	}

	/**
	 * @see ReportDAO#purgeReportRequest(ReportRequest)
	 */
	public void purgeReportRequest(ReportRequest request) {
		getSession().remove(request);
	}

	/**
	 * @see ReportDAO#purgeReportRequestsForReportDefinition(String)
	 */
	@Override
	public void purgeReportRequestsForReportDefinition(String reportDefinitionUuid) {
		String hql = "delete from ReportRequest r where r.reportDefinition.definition=:uuid";
		MutationQuery query = getSession().createMutationQuery(hql);
		query.setParameter("uuid", reportDefinitionUuid);
		query.executeUpdate();
	}


	/**
	 * @see ReportDAO#purgeReportDesignsForReportDefinition(String)
	 */
	@Override
	public void purgeReportDesignsForReportDefinition(String reportDefinitionUuid) {
		String hql = "delete from ReportDesign r where r.reportDefinition=:reportDefinition";
		MutationQuery query = getSession().createMutationQuery(hql);
		// the reportDefinition property is mapped by ReportDefinitionType, which binds the uuid of the definition
		ReportDefinition reportDefinition = new ReportDefinition();
		reportDefinition.setUuid(reportDefinitionUuid);
		query.setParameter("reportDefinition", reportDefinition);
		query.executeUpdate();
	}

	/**
	 * @see ReportDAO#getReportRequestUuids(String)
	 */
	@Override
	public List<String> getReportRequestUuids(String reportDefinitionUuid) {
		String hql = "select r.uuid from ReportRequest r where r.reportDefinition.definition=:uuid";
		Query<String> query = getSession().createQuery(hql, String.class);
		query.setParameter("uuid", reportDefinitionUuid);
		return query.list();
	}

	//***** PROPERTY ACCESS *****

	/**
	 * @return the sessionFactory
	 */
	public DbSessionFactory getSessionFactory() {
		return sessionFactory;
	}

	/**
	 * @param sessionFactory the sessionFactory to set
	 */
	public void setSessionFactory(DbSessionFactory sessionFactory) {
		this.sessionFactory = sessionFactory;
	}

	private Session getSession() {
		return sessionFactory.getHibernateSessionFactory().getCurrentSession();
	}

	private void setParameters(Query<?> query, Map<String, Object> params) {
		for (Map.Entry<String, Object> e : params.entrySet()) {
			if (e.getValue() instanceof Collection) {
				query.setParameterList(e.getKey(), (Collection<?>) e.getValue());
			}
			else {
				query.setParameter(e.getKey(), e.getValue());
			}
		}
	}

	private String createReportRequestsWhereClause(Map<String, Object> params, ReportDefinition reportDefinition, Date requestOnOrAfter, Date requestOnOrBefore, Status... statuses) {
		StringBuilder where = new StringBuilder(" where 1 = 1");

		if (reportDefinition != null) {
			where.append(" and r.reportDefinition.definition = :reportDefinitionUuid");
			params.put("reportDefinitionUuid", reportDefinition.getUuid());
		}
		if (requestOnOrAfter != null) {
			where.append(" and r.requestDate >= :requestOnOrAfter");
			params.put("requestOnOrAfter", requestOnOrAfter);
		}
		if (requestOnOrBefore != null) {
			where.append(" and r.requestDate <= :requestOnOrBefore");
			params.put("requestOnOrBefore", requestOnOrBefore);
		}
		if (statuses != null && statuses.length > 0) {
			where.append(" and r.status in (:statuses)");
			params.put("statuses", Arrays.asList(statuses));
		}

		return where.toString();
	}
}

